#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/cloud_vendor?useSSL=false
#    username: root
#    password: Thilanka@1234
#
#
#    #JPA Settings
#    jpa.hibernate.ddl_auto: create
#
#

#
##Working sql settings
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/cloud_vendor?useSSL=false
#    username: root
#    password: Thilanka@1234
#
#  # JPA Settings
#  jpa:
#    hibernate:
#      ddl-auto: create
#
#
##end





spring:
  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: sa
    password: sa
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop






